[package]
name = "kamulet_roguelike"
version = "0.2.1"
edition = "2021"
author = "Koma"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"